:navtitle: Enabling persistent storage in workspaces
:keywords: user-guide, configuring, user, volumes, persistent, volume, claim, mounting, mount
:page-aliases:

[id="enabling-persistent-storage-in-workspaces_{context}"]
= Enabling persistent storage in workspaces

{prod-short} workspaces and workspace data are ephemeral and are lost when the workspace stops.

To preserve the workspace state in persistent storage while the workspace is stopped, request a {kubernetes} PersistentVolume (PV) for the `{devworkspace}` containers in the {orch-name} cluster of your organization's {prod-short} instance.

You can request a PV by using the devfile or a {kubernetes} PersistentVolumeClaim (PVC).

An example of a PV is the `/projects/` directory of a workspace, which is mounted by default for non-ephemeral workspaces.

Persistent Volumes come at a cost: attaching a persistent volume slows workspace startup.

[WARNING]
====
Starting another, concurrently running workspace with a link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[`ReadWriteOnce` PV] may fail.
====

.Additional resources

* link:https://docs.openshift.com/container-platform/latest/storage/understanding-persistent-storage.html[Red Hat OpenShift Documentation: Understanding persistent storage]
* link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Kubernetes Documentation: Persistent Volumes]

== Requesting persistent storage in a devfile

When a workspace requires its own persistent storage, request a PersistentVolume (PV) in the devfile, and {prod-short} will automatically manage the necessary PersistentVolumeClaims.

.Prerequisites

* You have not started the workspace.

.Procedure

. Add a `volume` component in the devfile:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
...
components:
  ...
  - name: __<chosen_volume_name>__
    volume:
      size: __<requested_volume_size>__G
  ...
----

. Add a `volumeMount` for the relevant `container` in the devfile:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
...
components:
  - name: ...
    container:
      ...
      volumeMounts:
        - name: __<chosen_volume_name_from_previous_step>__
          path: __<path_where_to_mount_the_PV>__
      ...
----

.A devfile that provisions a PV for a workspace to a container
====

When a workspace is started with the following devfile, the `cache` PV is provisioned to the `golang` container in the `./cache` container path:

[source,yaml,subs="+quotes,+attributes,+macros"]
----
schemaVersion: 2.1.0
metadata:
  name: mydevfile
components:
  - name: golang
    container:
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: cache
          path: /.cache
  - name: cache
    volume:
      size: 2Gi
----

====

== Requesting persistent storage in a PVC

You may opt to apply a PersistentVolumeClaim (PVC) to request a PersistentVolume (PV) for your workspaces in the following cases:

* Not all developers of the project need the PV.
* The PV lifecycle goes beyond the lifecycle of a single workspace.
* The data included in the PV are shared across workspaces.

TIP: You can apply a PVC to the `{devworkspace}` containers even if the workspace is ephemeral and its devfile contains the `controller.devfile.io/storage-type: ephemeral` attribute.

.Prerequisites

* You have not started the workspace.
* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* For CLI users: The `{orch-cli}` command-line tool is installed in the operating system you are using.
* A PVC is created in your user {orch-namespace} to mount to all `{devworkspace}` containers.

.Procedure

. Add the `controller.devfile.io/mount-to-devworkspace: true` label to the PVC.

+
[TIP]
====
CLI users can apply the label like so:

[subs="+quotes,+attributes,+macros"]
----
`$ {orch-cli} label persistentvolumeclaim __<PVC_name>__ \
          controller.devfile.io/mount-to-devworkspace=true`
----
====

. Optional: Use the annotations to configure how the PVC is mounted:
+
.Optional annotations
|===
| Annotation |Description

| `controller.devfile.io/mount-path:`
| The mount path for the PVC.

Defaults to `/tmp/__<PVC_name>__`.

| `controller.devfile.io/read-only:`
| Set to `'true'` or `'false'` to specify whether the PVC is to be mounted as read-only.

Defaults to `'false'`, resulting in the PVC mounted as read-write.
|===

.Mounting a read-only PVC
====
[source,yaml,subs="+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __<pvc_name>__
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
  annotations:
    controller.devfile.io/mount-path: __</example/directory>__ <1>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi <2>
  volumeName: __<pv_name>__
  storageClassName: manual
  volumeMode: Filesystem
----
<1> The mounted PV is available at `__</example/directory>__` in the workspace.
<2> Example size value of the requested storage.

====