:_content-type: CONCEPT
:description: Microsoft Visual Studio Code - Open Source IDE
:keywords: user-guide, selecting, IDE, select, selecting, editor, ide, vs-code, visual-studio, visual-studio-code, jetbrains, intellij, pycharm, theia, che-theia
:navtitle: Microsoft Visual Studio Code - Open Source
:page-aliases:

[id="microsoft-visual-studio-code-open-source-ide"]
= Microsoft Visual Studio Code - Open Source IDE

Microsoft Visual Studio Code - Open Source is the default cloud IDE in a new workspace.

== Default `VS Code` extensions

{prod-short} adds these extensions:

Commands::
Translates Devfile commands to Microsoft Visual Studio Code - Open Source tasks.
+
.Procedure
* To see the drop-down list of available tasks, type: kbd:[F1] `Tasks: Run Task` kbd:[Enter] `che`.

Activity tracker::
Tracks events provided by the Microsoft Visual Studio Code - Open Source to determine and stop inactive workspaces.
This extension does not save, collect, or store data.

API::
Provides helpers to interact with {devworkspace} and {prod-short}.

GitHub authentication::
Provides support for authenticating to GitHub.
It registers the `github` Authentication Provider that can be leveraged by other extensions.
This also provides the GitHub authentication used by Settings Sync.

Port::
Detects opening ports and provides redirect URI.
When a process starts listening to a port, {prod-short} displays a notification with a link to open the resulting resource.
+
.Procedure
* To display the endpoint list, type: kbd:[F1] `Explorer: Focus on endpoints View` kbd:[Enter].

Remote::
Provides commands for the remote authority.

Resource monitor::
Monitors resources such as CPU and RAM.

Telemetry::
Detects and sends the following events to a backend telemetry plugin listening on `\http://localhost:$\{DEVWORKSPACE_TELEMETRY_BACKEND_PORT}`:

`WORKSPACE_OPENED`:::
Sent when the telemetry extension activates

`EDITOR_USED`:::
Sent on the `vscode.workspace.onDidChangeTextDocument` event

Terminal::
Opens a terminal to a {devworkspace} container.

NOTE: Because the {prod-short} build of Microsoft Visual Studio Code - Open Source supports custom branding, your organization might be using a branded build.

== Adding `VS Code` extensions

To enable the loaded Microsoft Visual Studio Code - Open Source in a workspace to automatically install selected extensions, you have to add an `extensions.json` file into the remote Git repository that contains your project source code and that will be cloned into workspaces.

.Prerequisites
* {prod-short} has access to the link:https://www.open-vsx.org/[OpenVSX registry].
+
[TIP]
====
To install recommended extensions in a restricted environment, consider these options:

* xref:administration-guide:configuring-the-open-vsx-registry-url.adoc[] to point to your OpenVSX registry.

* xref:defining-a-common-ide.adoc[].

* link:https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix[Installing extensions from VSX files].
====

.Procedure

. Create a `.vscode/extensions.json` file in the remote Git repository.

. Go to the link:https://www.open-vsx.org/[Open VSX registry], and while on the extension page, copy the **Unique_identifier** of each chosen extension and the publisher username from **Published_by** into the `extensions.json` file:
+
[source,json,subs="+quotes"]
----
  {
    "recommendations": [
      "__<Published_by_A>__.__<Unique_identifier_1>__",
      "__<Published_by_B>__.__<Unique_identifier_2>__",
      "__<Published_by_C>__.__<Unique_identifier_3>__"
    ]
  }
----

.Additional resources
* link:https://www.open-vsx.org/[Open VSX registry - Extensions for Microsoft Visual Studio Code compatible editors]
* link:https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions[Microsoft Visual Studio Code - Workspace recommended extensions]
