:_content-type: PROCEDURE
:description:  Workspace IDEs
:keywords: configuring, workspace, editor, ide
:navtitle: Workspace IDEs
:page-aliases:

[id="workspace-ides"]
= Workspace IDEs

== Repository-level IDE configuration in {prod-short}

The most convenient way of using an IDE in {prod-short} is to store IDE configuration files directly in the remote Git repository that contains your project source code and that will be cloned into workspaces. This way, one common IDE configuration will be applied to all new workspaces that will feature a clone of that repository. Such IDE configuration files might include the following:

* xref:ide-choice-for-a-git-repository.adoc[The `/.che/che-editor.yaml` file] that stores a definition of the chosen IDE.

* IDE-specific configuration files that one would typically store locally for a desktop IDE. For example:
** xref:vs-code-extensions.adoc[The `/.vscode/extensions.json` file.]
* link:https://editorconfig.org/[The `/.editorconfig` file.]

== Supported in-browser IDEs

The default in-browser IDE in a new workspace is Microsoft Visual Studio Code - Open Source. Alternatively, you can choose another supported IDE. The following IDEs are supported:

.Supported in-browser IDEs 

[cols="1,1a,1a"]
|===
| IDE | `id` | Note

include::example$snip_{project-context}-table-of-supported-editors.adoc[]

|===

